#!/bin/bash
# Store Type creation script using curl
# Generated by Doctool

set -e

# Configuration - set these variables before running
KEYFACTOR_HOSTNAME="${KEYFACTOR_HOSTNAME}"
KEYFACTOR_API_PATH="${KEYFACTOR_API_PATH:-KeyfactorAPI}"
KEYFACTOR_AUTH_TOKEN="${KEYFACTOR_AUTH_TOKEN}"

echo "Creating store type: GcpCertMgr"
curl -s -X POST "https://${KEYFACTOR_HOSTNAME}/${KEYFACTOR_API_PATH}/CertificateStoreTypes" \
  -H "Authorization: Bearer ${KEYFACTOR_AUTH_TOKEN}" \
  -H "Content-Type: application/json" \
  -H "x-keyfactor-requested-with: APIClient" \
  -d '{
  "Name": "GCP Certificate Manager",
  "ShortName": "GcpCertMgr",
  "Capability": "GcpCertMgr",
  "ServerRequired": false,
  "BlueprintAllowed": false,
  "CustomAliasAllowed": "Required",
  "PowerShell": false,
  "PrivateKeyAllowed": "Required",
  "StorePathType": "",
  "StorePathValue": "",
  "SupportedOperations": {
    "Add": true,
    "Create": false,
    "Discovery": true,
    "Enrollment": false,
    "Remove": true
  },
  "PasswordOptions": {
    "Style": "Default",
    "EntrySupported": false,
    "StoreRequired": false
  },
  "Properties": [
    {
      "Name": "Location",
      "DisplayName": "Location (deprecated)",
      "Type": "String",
      "DependsOn": "",
      "DefaultValue": "",
      "Required": false,
      "IsPAMEligible": false,
      "Description": "**Deprecated in v1.2.** The GCP location is parsed from Store Path. Leave blank for new stores. v1.1-shape stores (where Store Path is blank or `n/a`) still read this value as a fallback; expect a deprecation warning in the orchestrator log when that path is used."
    },
    {
      "Name": "ServiceAccountKey",
      "DisplayName": "Service Account Key File Path (deprecated)",
      "Type": "String",
      "DependsOn": "",
      "DefaultValue": "",
      "Required": false,
      "IsPAMEligible": false,
      "Description": "**Deprecated in v1.2.** Leave blank. Authenticate via Application Default Credentials instead (set `GOOGLE_APPLICATION_CREDENTIALS` as a machine-level environment variable on the orchestrator host pointing at the JSON key, or run on a GCE VM / GKE pod with workload identity). The Discovery job has no way to surface this custom property in Keyfactor Command's discovery-job UI, so ADC is the only mechanism that works uniformly across all four job types. v1.1 stores that have this populated continue to work via a deprecation-logged fallback; the field is scheduled for removal in v2.0."
    }
  ],
  "EntryParameters": [
    {
      "Name": "Scope",
      "DisplayName": "Certificate Scope",
      "Type": "MultipleChoice",
      "DependsOn": "",
      "DefaultValue": "DEFAULT",
      "Options": "DEFAULT,ALL_REGIONS,EDGE_CACHE,CLIENT_AUTH",
      "RequiredWhen": {
        "HasPrivateKey": false,
        "OnAdd": false,
        "OnRemove": false,
        "OnReenrollment": false
      },
      "Description": "GCP Certificate Manager `scope` for this certificate entry. Allowed: DEFAULT, ALL_REGIONS, EDGE_CACHE, CLIENT_AUTH. Immutable in GCP - cannot be changed after create. Inventory persists the existing scope back from GCP so renewals carry it forward automatically."
    }
  ]
}'

